name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 15
targetAbi: "10.9.7.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |-
  - Fix test badge typo (#257) @RyanMelena
  - Fix test status badge (#256) @RyanMelena
  - Make "Original Aspect Ratio" property available to WebHooks (#249) @RyanMelena

  ### Breaking changes ###
  - Allow smtp connection without SSL (#258) @RyanMelena

  ### Bug Fixes ###
  - Allow smtp connection without SSL (#258) @RyanMelena

  ### Dependency updates ###
  - chore(deps): update dependency mailkit to v4.7.0 (#174) @renovate
  - chore(deps): update dependency mqttnet.extensions.managedclient to v4.3.6.1152 (#246) @renovate
