name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 18
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Administration"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |-
  - Jellyfin 10.11 support (#328) @crobibero
  - Fix the problem of html escape of "Description" in Chinese. (#320) @sqliu07

  ### New features and improvements ###
  - Add json_encode helper mostly for {{{Overview}}} (#339) @mfedderly
