name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 16
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |-
  - 10.10 (#296) @crobibero
  - Add notification for item deleted (#285) @chiragkrishna
  - Add NotificationUsername & ClientName to authentication failure (#284) @chiragkrishna
  - Add Enable/Disable options for webhooks (#283) @chiragkrishna
  - ntfy.sh: Template Optimizations Pt. 2 (#277) @v3DJG6GL
  - Added Gotify handlebars (#278) @chiragkrishna
  - Added Telegram handlebars (#279) @chiragkrishna
  - Expose RemoteEndPoint & SessionInfo Variables (#275) @chiragkrishna
  - Fix SessionStart double notifications (#272) @chiragkrishna
  - Add option for Item type videos (#274) @chiragkrishna
  - Add RemoteEndPoint variable (#273) @chiragkrishna
  - Fix duplicate and wrong notification types for Pushover templates (#270) @Luka-He
  - ntfy.sh: Template Optimizations (#268) @v3DJG6GL

  ### Documentation updates ###
  - Update README.md (#271) @chiragkrishna

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to 8.0.1 (#290) @renovate
  - Update dependency MailKit to 4.8.0 (#288) @renovate
  - Update dependency MQTTnet.Extensions.ManagedClient to 4.3.7.1207 (#280) @renovate
  - chore(deps): update dependency mailkit to v4.7.1.1 (#263) @renovate
