name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 19
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Administration"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |-
  - fix: accept non-string JSON and convert to strings for form encoding (#348) @MattKobayashi

  ### Dependency updates ###
  - Update dependency MailKit to 4.14.1 - autoclosed (#310) @[renovate[bot]](https://github.com/apps/renovate)
  - Update dependency Microsoft.Extensions.Http to v10 (#357) @[renovate[bot]](https://github.com/apps/renovate)
  - Update dependency Microsoft.Extensions.Http to 9.0.11 (#350) @[renovate[bot]](https://github.com/apps/renovate)
