name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml@master
    with:
      version: ${{ github.event.release.tag_name }}
      is-unstable: ${{ github.event.release.prerelease }}
    secrets:
      deploy-host: ${{ secrets.DEPLOY_HOST }}
      deploy-user: ${{ secrets.DEPLOY_USER }}
      deploy-key: ${{ secrets.DEPLOY_KEY }}
